apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: cotype
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: co-type/broker:latest
          imagePullPolicy: Never
          ports:
            - name: discovery
              containerPort: {{ .Values.discoveryPort }}
            - name: control
              containerPort: {{ .Values.controlPort }}
          env:
            - name: DISCOVERY_PORT
              value: "{{ .Values.discoveryPort }}"
            - name: CONTROL_PORT
              value: "{{ .Values.controlPort }}"
