apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: cotype
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - name: gateway
      port: {{ .Values.gatewayPort }}
      targetPort: {{ .Values.gatewayPort }}
      nodePort: 30051 # clients outside the cluster connect to $(minikube ip):30051
    - name: control
      port: {{ .Values.controlPort }}
      targetPort: {{ .Values.controlPort }}
      nodePort: 30052 # game servers connect to broker:50052 from inside the cluster
