---
apiVersion: v1
kind: Service
metadata:
  name: gameserver-0
  namespace: cotype
spec:
  type: NodePort
  selector:
    app: gameserver
    statefulset.kubernetes.io/pod-name: gameserver-0
  ports:
    - port: {{ .Values.matchPort }}
      targetPort: {{ .Values.matchPort }}
      nodePort: {{ add .Values.matchNodePort 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: gameserver-1
  namespace: cotype
spec:
  type: NodePort
  selector:
    app: gameserver
    statefulset.kubernetes.io/pod-name: gameserver-1
  ports:
    - port: {{ .Values.matchPort }}
      targetPort: {{ .Values.matchPort }}
      nodePort: {{ add .Values.matchNodePort 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: gameserver-2
  namespace: cotype
spec:
  type: NodePort
  selector:
    app: gameserver
    statefulset.kubernetes.io/pod-name: gameserver-2
  ports:
    - port: {{ .Values.matchPort }}
      targetPort: {{ .Values.matchPort }}
      nodePort: {{ add .Values.matchNodePort 2 }}
