// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: common/proto/discovery/discovery.proto

package discovery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryService_AvailableServer_FullMethodName    = "/discovery.DiscoveryService/AvailableServer"
	DiscoveryService_ServerHostingLobby_FullMethodName = "/discovery.DiscoveryService/ServerHostingLobby"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The discovery service definition.
type DiscoveryServiceClient interface {
	// RPC to get the available server information.
	AvailableServer(ctx context.Context, in *AvailableServerRequest, opts ...grpc.CallOption) (*AvailableServerResponse, error)
	// RPC to get the server hosting lobby information.
	ServerHostingLobby(ctx context.Context, in *ServerHostingLobbyRequest, opts ...grpc.CallOption) (*ServerHostingLobbyResponse, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) AvailableServer(ctx context.Context, in *AvailableServerRequest, opts ...grpc.CallOption) (*AvailableServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailableServerResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_AvailableServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) ServerHostingLobby(ctx context.Context, in *ServerHostingLobbyRequest, opts ...grpc.CallOption) (*ServerHostingLobbyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerHostingLobbyResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_ServerHostingLobby_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations must embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
//
// The discovery service definition.
type DiscoveryServiceServer interface {
	// RPC to get the available server information.
	AvailableServer(context.Context, *AvailableServerRequest) (*AvailableServerResponse, error)
	// RPC to get the server hosting lobby information.
	ServerHostingLobby(context.Context, *ServerHostingLobbyRequest) (*ServerHostingLobbyResponse, error)
	mustEmbedUnimplementedDiscoveryServiceServer()
}

// UnimplementedDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) AvailableServer(context.Context, *AvailableServerRequest) (*AvailableServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AvailableServer not implemented")
}
func (UnimplementedDiscoveryServiceServer) ServerHostingLobby(context.Context, *ServerHostingLobbyRequest) (*ServerHostingLobbyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServerHostingLobby not implemented")
}
func (UnimplementedDiscoveryServiceServer) mustEmbedUnimplementedDiscoveryServiceServer() {}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_AvailableServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).AvailableServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_AvailableServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).AvailableServer(ctx, req.(*AvailableServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_ServerHostingLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerHostingLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).ServerHostingLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_ServerHostingLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).ServerHostingLobby(ctx, req.(*ServerHostingLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvailableServer",
			Handler:    _DiscoveryService_AvailableServer_Handler,
		},
		{
			MethodName: "ServerHostingLobby",
			Handler:    _DiscoveryService_ServerHostingLobby_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/discovery/discovery.proto",
}
