syntax = "proto3";

package discovery;

option go_package = "github.com/sceredi/co-type/common/proto/discovery";

// The discovery service definition.
service DiscoveryService {
  // RPC to get the available server information.
  rpc AvailableServer(AvailableServerRequest) returns (AvailableServerResponse);

  // RPC to get the server hosting lobby information.
  rpc ServerHostingLobby(ServerHostingLobbyRequest) returns (ServerHostingLobbyResponse);
}

// Request message for available server information.
message AvailableServerRequest{}

// Response message containing available server information.
message AvailableServerResponse {
  string name = 1;
  string addr = 2;
  int64 port = 3;
}

// Request message for server hosting lobby information.
message ServerHostingLobbyRequest {
  string lobby_id = 1;
}

// Response message containing server hosting lobby information.
message ServerHostingLobbyResponse {
  string name = 1;
  string addr = 2;
  int64 port = 3;
}
