syntax = "proto3";

package lobby;

option go_package = "github.com/sceredi/co-type/common/proto/lobby";

// The game service definition.
service LobbyService {
  rpc CreateLobby(CreateLobbyRequest) returns (CreateLobbyResponse);
  rpc JoinLobby(JoinLobbyRequest) returns (JoinLobbyResponse);
  rpc LeaveLobby(LeaveLobbyRequest) returns (LeaveLobbyResponse);
  rpc EditPlayer(EditPlayerRequest) returns (EditPlayerResponse);
  rpc ReadyPlayer(ReadyPlayerRequest) returns (ReadyPlayerResponse);
  rpc Subscribe(SubscribeRequest) returns (stream LobbyEvent);
}

enum LobbyStatus {
  WAITING_FOR_PLAYERS = 0;
  PLAYING = 1;
  PAUSED = 2;
  GAME_ENDED = 3;
}

message GameInfo {
  string snippet = 1;
  int64 correct_chars = 2;
  int64 wrong_chars = 3;
  int64 revision = 4;
}

message Lobby {
  string id = 1;
  repeated Player players = 2;
  GameInfo game = 3;
  LobbyStatus status = 4;
}

message Player {
  string name = 1;
  bool is_ready = 2;
  string allowed_characters = 3;
  string blocked_characters = 4;
  bool can_delete = 5;
}

// Messages for lobby management.
message CreateLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message CreateLobbyResponse {
  Lobby lobby = 1;
}

message JoinLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message JoinLobbyResponse {
  Lobby lobby = 1;
}

message LeaveLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message LeaveLobbyResponse {
  bool success = 1;
  string message = 2;
}

message EditPlayerRequest {
  string lobby_id = 1;
  string player_name = 2;
  bool is_ready = 3;
  string allowed_characters = 4;
  string blocked_characters = 5;
  bool can_delete = 6;
}

message EditPlayerResponse {
  Lobby lobby = 1;
}

message ReadyPlayerRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message ReadyPlayerResponse {
  Lobby lobby = 1;
}

message SubscribeRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message LobbyEvent {
  Lobby lobby = 1;
}
