syntax = "proto3";

package lobby;

option go_package = "github.com/sceredi/co-type/common/proto/lobby";

// The game service definition.
service LobbyService {
  rpc CreateLobby(CreateLobbyRequest) returns (CreateLobbyResponse);
  rpc JoinLobby(JoinLobbyRequest) returns (JoinLobbyResponse);
  rpc LeaveLobby(LeaveLobbyRequest) returns (LeaveLobbyResponse);
  rpc Subscribe(SubscribeRequest) returns (stream LobbyEvent);
}

message Lobby {
  string id = 1;
  repeated Player players = 2;
  Player host = 3;
  string snippet = 4;
}

message Player {
  string name = 1;
  bool is_ready = 2;
  string allowed_characters = 3;
  string blocked_characters = 4;
  bool can_delete = 5;
}

// Messages for lobby management.
message CreateLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message CreateLobbyResponse {
  Lobby lobby = 1;
}

message JoinLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message JoinLobbyResponse {
  Lobby lobby = 1;
}

message LeaveLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message LeaveLobbyResponse {
  bool success = 1;
  string message = 2;
}

message SubscribeRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message LobbyEvent {
  Lobby lobby = 1;
}
