syntax = "proto3";

package lobby;

option go_package = "github.com/sceredi/co-type/common/proto/lobby";

// The game service definition.
service LobbyService {
  rpc CreateLobby(CreateLobbyRequest) returns (CreateLobbyResponse);
  rpc Subscribe(SubscribeRequest) returns (stream LobbyEvent);
}

// Messages for lobby management.
message CreateLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message CreateLobbyResponse {}

message SubscribeRequest {
  string lobby_id = 1;
  string player_name = 2;
}

message LobbyEvent {
  oneof event {
    PlayerJoin player_join = 1;
    PlayerLeave player_leave = 2;
    PlayerReady player_ready = 3;
    PlayerEdit player_edit = 4;
  }
}

message PlayerJoin {
  string player_name = 1;
}

message PlayerLeave {
  string player_name = 1;
}

message PlayerReady {
  string player_name = 1;
  bool is_ready = 2;
}

message PlayerEdit {
  string player_name = 1;
  string allowed_characters = 2;
  string blocked_characters = 3;
  bool can_delete = 4;
}


// Messages for joining a lobby.
message JoinLobbyRequest {
  string lobby_id = 1;
  string player_name = 2;
}

// Acknowledgment for joining a lobby.
message JoinLobbyResponse {}
