// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/proto/lobby/lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Host          *Player                `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Snippet       string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lobby) Reset() {
	*x = Lobby{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lobby) ProtoMessage() {}

func (x *Lobby) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lobby.ProtoReflect.Descriptor instead.
func (*Lobby) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *Lobby) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lobby) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Lobby) GetHost() *Player {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Lobby) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type Player struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsReady           bool                   `protobuf:"varint,2,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	AllowedCharacters string                 `protobuf:"bytes,3,opt,name=allowed_characters,json=allowedCharacters,proto3" json:"allowed_characters,omitempty"`
	BlockedCharacters string                 `protobuf:"bytes,4,opt,name=blocked_characters,json=blockedCharacters,proto3" json:"blocked_characters,omitempty"`
	CanDelete         bool                   `protobuf:"varint,5,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *Player) GetAllowedCharacters() string {
	if x != nil {
		return x.AllowedCharacters
	}
	return ""
}

func (x *Player) GetBlockedCharacters() string {
	if x != nil {
		return x.BlockedCharacters
	}
	return ""
}

func (x *Player) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

// Messages for lobby management.
type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *CreateLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type JoinLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *JoinLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *JoinLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type JoinLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyResponse) Reset() {
	*x = JoinLobbyResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyResponse) ProtoMessage() {}

func (x *JoinLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *JoinLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type LeaveLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyRequest) Reset() {
	*x = LeaveLobbyRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyRequest) ProtoMessage() {}

func (x *LeaveLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyRequest.ProtoReflect.Descriptor instead.
func (*LeaveLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *LeaveLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type LeaveLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyResponse) Reset() {
	*x = LeaveLobbyResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyResponse) ProtoMessage() {}

func (x *LeaveLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyResponse.ProtoReflect.Descriptor instead.
func (*LeaveLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveLobbyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *SubscribeRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type LobbyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyEvent) Reset() {
	*x = LobbyEvent{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyEvent) ProtoMessage() {}

func (x *LobbyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyEvent.ProtoReflect.Descriptor instead.
func (*LobbyEvent) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{9}
}

func (x *LobbyEvent) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

var File_common_proto_lobby_lobby_proto protoreflect.FileDescriptor

const file_common_proto_lobby_lobby_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/proto/lobby/lobby.proto\x12\x05lobby\"}\n" +
	"\x05Lobby\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\aplayers\x18\x02 \x03(\v2\r.lobby.PlayerR\aplayers\x12!\n" +
	"\x04host\x18\x03 \x01(\v2\r.lobby.PlayerR\x04host\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\"\xb4\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bis_ready\x18\x02 \x01(\bR\aisReady\x12-\n" +
	"\x12allowed_characters\x18\x03 \x01(\tR\x11allowedCharacters\x12-\n" +
	"\x12blocked_characters\x18\x04 \x01(\tR\x11blockedCharacters\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x05 \x01(\bR\tcanDelete\"P\n" +
	"\x12CreateLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"9\n" +
	"\x13CreateLobbyResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"N\n" +
	"\x10JoinLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"7\n" +
	"\x11JoinLobbyResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"O\n" +
	"\x11LeaveLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"H\n" +
	"\x12LeaveLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"0\n" +
	"\n" +
	"LobbyEvent\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby2\x92\x02\n" +
	"\fLobbyService\x12D\n" +
	"\vCreateLobby\x12\x19.lobby.CreateLobbyRequest\x1a\x1a.lobby.CreateLobbyResponse\x12>\n" +
	"\tJoinLobby\x12\x17.lobby.JoinLobbyRequest\x1a\x18.lobby.JoinLobbyResponse\x12A\n" +
	"\n" +
	"LeaveLobby\x12\x18.lobby.LeaveLobbyRequest\x1a\x19.lobby.LeaveLobbyResponse\x129\n" +
	"\tSubscribe\x12\x17.lobby.SubscribeRequest\x1a\x11.lobby.LobbyEvent0\x01B/Z-github.com/sceredi/co-type/common/proto/lobbyb\x06proto3"

var (
	file_common_proto_lobby_lobby_proto_rawDescOnce sync.Once
	file_common_proto_lobby_lobby_proto_rawDescData []byte
)

func file_common_proto_lobby_lobby_proto_rawDescGZIP() []byte {
	file_common_proto_lobby_lobby_proto_rawDescOnce.Do(func() {
		file_common_proto_lobby_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_lobby_lobby_proto_rawDesc), len(file_common_proto_lobby_lobby_proto_rawDesc)))
	})
	return file_common_proto_lobby_lobby_proto_rawDescData
}

var file_common_proto_lobby_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_common_proto_lobby_lobby_proto_goTypes = []any{
	(*Lobby)(nil),               // 0: lobby.Lobby
	(*Player)(nil),              // 1: lobby.Player
	(*CreateLobbyRequest)(nil),  // 2: lobby.CreateLobbyRequest
	(*CreateLobbyResponse)(nil), // 3: lobby.CreateLobbyResponse
	(*JoinLobbyRequest)(nil),    // 4: lobby.JoinLobbyRequest
	(*JoinLobbyResponse)(nil),   // 5: lobby.JoinLobbyResponse
	(*LeaveLobbyRequest)(nil),   // 6: lobby.LeaveLobbyRequest
	(*LeaveLobbyResponse)(nil),  // 7: lobby.LeaveLobbyResponse
	(*SubscribeRequest)(nil),    // 8: lobby.SubscribeRequest
	(*LobbyEvent)(nil),          // 9: lobby.LobbyEvent
}
var file_common_proto_lobby_lobby_proto_depIdxs = []int32{
	1, // 0: lobby.Lobby.players:type_name -> lobby.Player
	1, // 1: lobby.Lobby.host:type_name -> lobby.Player
	0, // 2: lobby.CreateLobbyResponse.lobby:type_name -> lobby.Lobby
	0, // 3: lobby.JoinLobbyResponse.lobby:type_name -> lobby.Lobby
	0, // 4: lobby.LobbyEvent.lobby:type_name -> lobby.Lobby
	2, // 5: lobby.LobbyService.CreateLobby:input_type -> lobby.CreateLobbyRequest
	4, // 6: lobby.LobbyService.JoinLobby:input_type -> lobby.JoinLobbyRequest
	6, // 7: lobby.LobbyService.LeaveLobby:input_type -> lobby.LeaveLobbyRequest
	8, // 8: lobby.LobbyService.Subscribe:input_type -> lobby.SubscribeRequest
	3, // 9: lobby.LobbyService.CreateLobby:output_type -> lobby.CreateLobbyResponse
	5, // 10: lobby.LobbyService.JoinLobby:output_type -> lobby.JoinLobbyResponse
	7, // 11: lobby.LobbyService.LeaveLobby:output_type -> lobby.LeaveLobbyResponse
	9, // 12: lobby.LobbyService.Subscribe:output_type -> lobby.LobbyEvent
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_proto_lobby_lobby_proto_init() }
func file_common_proto_lobby_lobby_proto_init() {
	if File_common_proto_lobby_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_lobby_lobby_proto_rawDesc), len(file_common_proto_lobby_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_lobby_lobby_proto_goTypes,
		DependencyIndexes: file_common_proto_lobby_lobby_proto_depIdxs,
		MessageInfos:      file_common_proto_lobby_lobby_proto_msgTypes,
	}.Build()
	File_common_proto_lobby_lobby_proto = out.File
	file_common_proto_lobby_lobby_proto_goTypes = nil
	file_common_proto_lobby_lobby_proto_depIdxs = nil
}
