// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: common/proto/lobby/lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LobbyStatus int32

const (
	LobbyStatus_WAITING_FOR_PLAYERS LobbyStatus = 0
	LobbyStatus_PLAYING             LobbyStatus = 1
	LobbyStatus_PAUSED              LobbyStatus = 2
	LobbyStatus_GAME_ENDED          LobbyStatus = 3
)

// Enum value maps for LobbyStatus.
var (
	LobbyStatus_name = map[int32]string{
		0: "WAITING_FOR_PLAYERS",
		1: "PLAYING",
		2: "PAUSED",
		3: "GAME_ENDED",
	}
	LobbyStatus_value = map[string]int32{
		"WAITING_FOR_PLAYERS": 0,
		"PLAYING":             1,
		"PAUSED":              2,
		"GAME_ENDED":          3,
	}
)

func (x LobbyStatus) Enum() *LobbyStatus {
	p := new(LobbyStatus)
	*p = x
	return p
}

func (x LobbyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LobbyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_lobby_lobby_proto_enumTypes[0].Descriptor()
}

func (LobbyStatus) Type() protoreflect.EnumType {
	return &file_common_proto_lobby_lobby_proto_enumTypes[0]
}

func (x LobbyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LobbyStatus.Descriptor instead.
func (LobbyStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

type GameInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Snippet      string                 `protobuf:"bytes,1,opt,name=snippet,proto3" json:"snippet,omitempty"`
	CorrectChars int64                  `protobuf:"varint,2,opt,name=correct_chars,json=correctChars,proto3" json:"correct_chars,omitempty"`
	WrongChars   int64                  `protobuf:"varint,3,opt,name=wrong_chars,json=wrongChars,proto3" json:"wrong_chars,omitempty"`
	Revision     int64                  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	// start_time_ms is the Unix timestamp in milliseconds when the game started.
	StartTimeMs int64 `protobuf:"varint,5,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	// elapsed_ms is the total game duration in milliseconds, set when the game ends.
	ElapsedMs     int64 `protobuf:"varint,6,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *GameInfo) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *GameInfo) GetCorrectChars() int64 {
	if x != nil {
		return x.CorrectChars
	}
	return 0
}

func (x *GameInfo) GetWrongChars() int64 {
	if x != nil {
		return x.WrongChars
	}
	return 0
}

func (x *GameInfo) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *GameInfo) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *GameInfo) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type Lobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Game          *GameInfo              `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	Status        LobbyStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=lobby.LobbyStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lobby) Reset() {
	*x = Lobby{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lobby) ProtoMessage() {}

func (x *Lobby) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lobby.ProtoReflect.Descriptor instead.
func (*Lobby) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *Lobby) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lobby) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Lobby) GetGame() *GameInfo {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *Lobby) GetStatus() LobbyStatus {
	if x != nil {
		return x.Status
	}
	return LobbyStatus_WAITING_FOR_PLAYERS
}

type Player struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsReady           bool                   `protobuf:"varint,2,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	AllowedCharacters string                 `protobuf:"bytes,3,opt,name=allowed_characters,json=allowedCharacters,proto3" json:"allowed_characters,omitempty"`
	BlockedCharacters string                 `protobuf:"bytes,4,opt,name=blocked_characters,json=blockedCharacters,proto3" json:"blocked_characters,omitempty"`
	CanDelete         bool                   `protobuf:"varint,5,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *Player) GetAllowedCharacters() string {
	if x != nil {
		return x.AllowedCharacters
	}
	return ""
}

func (x *Player) GetBlockedCharacters() string {
	if x != nil {
		return x.BlockedCharacters
	}
	return ""
}

func (x *Player) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

// Messages for lobby management.
type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *CreateLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type JoinLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *JoinLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *JoinLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type JoinLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyResponse) Reset() {
	*x = JoinLobbyResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyResponse) ProtoMessage() {}

func (x *JoinLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *JoinLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type LeaveLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyRequest) Reset() {
	*x = LeaveLobbyRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyRequest) ProtoMessage() {}

func (x *LeaveLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyRequest.ProtoReflect.Descriptor instead.
func (*LeaveLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *LeaveLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type LeaveLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyResponse) Reset() {
	*x = LeaveLobbyResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyResponse) ProtoMessage() {}

func (x *LeaveLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyResponse.ProtoReflect.Descriptor instead.
func (*LeaveLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveLobbyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EditPlayerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LobbyId           string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName        string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	IsReady           bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	AllowedCharacters string                 `protobuf:"bytes,4,opt,name=allowed_characters,json=allowedCharacters,proto3" json:"allowed_characters,omitempty"`
	BlockedCharacters string                 `protobuf:"bytes,5,opt,name=blocked_characters,json=blockedCharacters,proto3" json:"blocked_characters,omitempty"`
	CanDelete         bool                   `protobuf:"varint,6,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EditPlayerRequest) Reset() {
	*x = EditPlayerRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlayerRequest) ProtoMessage() {}

func (x *EditPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlayerRequest.ProtoReflect.Descriptor instead.
func (*EditPlayerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{9}
}

func (x *EditPlayerRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *EditPlayerRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *EditPlayerRequest) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *EditPlayerRequest) GetAllowedCharacters() string {
	if x != nil {
		return x.AllowedCharacters
	}
	return ""
}

func (x *EditPlayerRequest) GetBlockedCharacters() string {
	if x != nil {
		return x.BlockedCharacters
	}
	return ""
}

func (x *EditPlayerRequest) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

type EditPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPlayerResponse) Reset() {
	*x = EditPlayerResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlayerResponse) ProtoMessage() {}

func (x *EditPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlayerResponse.ProtoReflect.Descriptor instead.
func (*EditPlayerResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{10}
}

func (x *EditPlayerResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type ReadyPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyPlayerRequest) Reset() {
	*x = ReadyPlayerRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyPlayerRequest) ProtoMessage() {}

func (x *ReadyPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyPlayerRequest.ProtoReflect.Descriptor instead.
func (*ReadyPlayerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{11}
}

func (x *ReadyPlayerRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *ReadyPlayerRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type ReadyPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyPlayerResponse) Reset() {
	*x = ReadyPlayerResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyPlayerResponse) ProtoMessage() {}

func (x *ReadyPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyPlayerResponse.ProtoReflect.Descriptor instead.
func (*ReadyPlayerResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{12}
}

func (x *ReadyPlayerResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *SubscribeRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type LobbyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyEvent) Reset() {
	*x = LobbyEvent{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyEvent) ProtoMessage() {}

func (x *LobbyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyEvent.ProtoReflect.Descriptor instead.
func (*LobbyEvent) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{14}
}

func (x *LobbyEvent) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type SendKeyPressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	IsBackspace   bool                   `protobuf:"varint,4,opt,name=is_backspace,json=isBackspace,proto3" json:"is_backspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendKeyPressRequest) Reset() {
	*x = SendKeyPressRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendKeyPressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyPressRequest) ProtoMessage() {}

func (x *SendKeyPressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyPressRequest.ProtoReflect.Descriptor instead.
func (*SendKeyPressRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{15}
}

func (x *SendKeyPressRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *SendKeyPressRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *SendKeyPressRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SendKeyPressRequest) GetIsBackspace() bool {
	if x != nil {
		return x.IsBackspace
	}
	return false
}

type SendKeyPressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendKeyPressResponse) Reset() {
	*x = SendKeyPressResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendKeyPressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKeyPressResponse) ProtoMessage() {}

func (x *SendKeyPressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKeyPressResponse.ProtoReflect.Descriptor instead.
func (*SendKeyPressResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{16}
}

func (x *SendKeyPressResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

// Request to resume a crashed game on a new server.
type ResumeGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeGameRequest) Reset() {
	*x = ResumeGameRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeGameRequest) ProtoMessage() {}

func (x *ResumeGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeGameRequest.ProtoReflect.Descriptor instead.
func (*ResumeGameRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{17}
}

func (x *ResumeGameRequest) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

func (x *ResumeGameRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// Response after resuming a game.
type ResumeGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeGameResponse) Reset() {
	*x = ResumeGameResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeGameResponse) ProtoMessage() {}

func (x *ResumeGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeGameResponse.ProtoReflect.Descriptor instead.
func (*ResumeGameResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{18}
}

func (x *ResumeGameResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

var File_common_proto_lobby_lobby_proto protoreflect.FileDescriptor

const file_common_proto_lobby_lobby_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/proto/lobby/lobby.proto\x12\x05lobby\"\xc9\x01\n" +
	"\bGameInfo\x12\x18\n" +
	"\asnippet\x18\x01 \x01(\tR\asnippet\x12#\n" +
	"\rcorrect_chars\x18\x02 \x01(\x03R\fcorrectChars\x12\x1f\n" +
	"\vwrong_chars\x18\x03 \x01(\x03R\n" +
	"wrongChars\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12\"\n" +
	"\rstart_time_ms\x18\x05 \x01(\x03R\vstartTimeMs\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x06 \x01(\x03R\telapsedMs\"\x91\x01\n" +
	"\x05Lobby\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\aplayers\x18\x02 \x03(\v2\r.lobby.PlayerR\aplayers\x12#\n" +
	"\x04game\x18\x03 \x01(\v2\x0f.lobby.GameInfoR\x04game\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.lobby.LobbyStatusR\x06status\"\xb4\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bis_ready\x18\x02 \x01(\bR\aisReady\x12-\n" +
	"\x12allowed_characters\x18\x03 \x01(\tR\x11allowedCharacters\x12-\n" +
	"\x12blocked_characters\x18\x04 \x01(\tR\x11blockedCharacters\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x05 \x01(\bR\tcanDelete\"P\n" +
	"\x12CreateLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"9\n" +
	"\x13CreateLobbyResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"N\n" +
	"\x10JoinLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"7\n" +
	"\x11JoinLobbyResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"O\n" +
	"\x11LeaveLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"H\n" +
	"\x12LeaveLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe7\x01\n" +
	"\x11EditPlayerRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\x12-\n" +
	"\x12allowed_characters\x18\x04 \x01(\tR\x11allowedCharacters\x12-\n" +
	"\x12blocked_characters\x18\x05 \x01(\tR\x11blockedCharacters\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x06 \x01(\bR\tcanDelete\"8\n" +
	"\x12EditPlayerResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"P\n" +
	"\x12ReadyPlayerRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"9\n" +
	"\x13ReadyPlayerResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"N\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"0\n" +
	"\n" +
	"LobbyEvent\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"\x86\x01\n" +
	"\x13SendKeyPressRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12!\n" +
	"\fis_backspace\x18\x04 \x01(\bR\visBackspace\":\n" +
	"\x14SendKeyPressResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"X\n" +
	"\x11ResumeGameRequest\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"8\n" +
	"\x12ResumeGameResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby*O\n" +
	"\vLobbyStatus\x12\x17\n" +
	"\x13WAITING_FOR_PLAYERS\x10\x00\x12\v\n" +
	"\aPLAYING\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02\x12\x0e\n" +
	"\n" +
	"GAME_ENDED\x10\x032\xa7\x04\n" +
	"\fLobbyService\x12D\n" +
	"\vCreateLobby\x12\x19.lobby.CreateLobbyRequest\x1a\x1a.lobby.CreateLobbyResponse\x12>\n" +
	"\tJoinLobby\x12\x17.lobby.JoinLobbyRequest\x1a\x18.lobby.JoinLobbyResponse\x12A\n" +
	"\n" +
	"LeaveLobby\x12\x18.lobby.LeaveLobbyRequest\x1a\x19.lobby.LeaveLobbyResponse\x12A\n" +
	"\n" +
	"EditPlayer\x12\x18.lobby.EditPlayerRequest\x1a\x19.lobby.EditPlayerResponse\x12D\n" +
	"\vReadyPlayer\x12\x19.lobby.ReadyPlayerRequest\x1a\x1a.lobby.ReadyPlayerResponse\x129\n" +
	"\tSubscribe\x12\x17.lobby.SubscribeRequest\x1a\x11.lobby.LobbyEvent0\x01\x12G\n" +
	"\fSendKeyPress\x12\x1a.lobby.SendKeyPressRequest\x1a\x1b.lobby.SendKeyPressResponse\x12A\n" +
	"\n" +
	"ResumeGame\x12\x18.lobby.ResumeGameRequest\x1a\x19.lobby.ResumeGameResponseB/Z-github.com/sceredi/co-type/common/proto/lobbyb\x06proto3"

var (
	file_common_proto_lobby_lobby_proto_rawDescOnce sync.Once
	file_common_proto_lobby_lobby_proto_rawDescData []byte
)

func file_common_proto_lobby_lobby_proto_rawDescGZIP() []byte {
	file_common_proto_lobby_lobby_proto_rawDescOnce.Do(func() {
		file_common_proto_lobby_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_lobby_lobby_proto_rawDesc), len(file_common_proto_lobby_lobby_proto_rawDesc)))
	})
	return file_common_proto_lobby_lobby_proto_rawDescData
}

var file_common_proto_lobby_lobby_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_lobby_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_common_proto_lobby_lobby_proto_goTypes = []any{
	(LobbyStatus)(0),             // 0: lobby.LobbyStatus
	(*GameInfo)(nil),             // 1: lobby.GameInfo
	(*Lobby)(nil),                // 2: lobby.Lobby
	(*Player)(nil),               // 3: lobby.Player
	(*CreateLobbyRequest)(nil),   // 4: lobby.CreateLobbyRequest
	(*CreateLobbyResponse)(nil),  // 5: lobby.CreateLobbyResponse
	(*JoinLobbyRequest)(nil),     // 6: lobby.JoinLobbyRequest
	(*JoinLobbyResponse)(nil),    // 7: lobby.JoinLobbyResponse
	(*LeaveLobbyRequest)(nil),    // 8: lobby.LeaveLobbyRequest
	(*LeaveLobbyResponse)(nil),   // 9: lobby.LeaveLobbyResponse
	(*EditPlayerRequest)(nil),    // 10: lobby.EditPlayerRequest
	(*EditPlayerResponse)(nil),   // 11: lobby.EditPlayerResponse
	(*ReadyPlayerRequest)(nil),   // 12: lobby.ReadyPlayerRequest
	(*ReadyPlayerResponse)(nil),  // 13: lobby.ReadyPlayerResponse
	(*SubscribeRequest)(nil),     // 14: lobby.SubscribeRequest
	(*LobbyEvent)(nil),           // 15: lobby.LobbyEvent
	(*SendKeyPressRequest)(nil),  // 16: lobby.SendKeyPressRequest
	(*SendKeyPressResponse)(nil), // 17: lobby.SendKeyPressResponse
	(*ResumeGameRequest)(nil),    // 18: lobby.ResumeGameRequest
	(*ResumeGameResponse)(nil),   // 19: lobby.ResumeGameResponse
}
var file_common_proto_lobby_lobby_proto_depIdxs = []int32{
	3,  // 0: lobby.Lobby.players:type_name -> lobby.Player
	1,  // 1: lobby.Lobby.game:type_name -> lobby.GameInfo
	0,  // 2: lobby.Lobby.status:type_name -> lobby.LobbyStatus
	2,  // 3: lobby.CreateLobbyResponse.lobby:type_name -> lobby.Lobby
	2,  // 4: lobby.JoinLobbyResponse.lobby:type_name -> lobby.Lobby
	2,  // 5: lobby.EditPlayerResponse.lobby:type_name -> lobby.Lobby
	2,  // 6: lobby.ReadyPlayerResponse.lobby:type_name -> lobby.Lobby
	2,  // 7: lobby.LobbyEvent.lobby:type_name -> lobby.Lobby
	2,  // 8: lobby.SendKeyPressResponse.lobby:type_name -> lobby.Lobby
	2,  // 9: lobby.ResumeGameRequest.lobby:type_name -> lobby.Lobby
	2,  // 10: lobby.ResumeGameResponse.lobby:type_name -> lobby.Lobby
	4,  // 11: lobby.LobbyService.CreateLobby:input_type -> lobby.CreateLobbyRequest
	6,  // 12: lobby.LobbyService.JoinLobby:input_type -> lobby.JoinLobbyRequest
	8,  // 13: lobby.LobbyService.LeaveLobby:input_type -> lobby.LeaveLobbyRequest
	10, // 14: lobby.LobbyService.EditPlayer:input_type -> lobby.EditPlayerRequest
	12, // 15: lobby.LobbyService.ReadyPlayer:input_type -> lobby.ReadyPlayerRequest
	14, // 16: lobby.LobbyService.Subscribe:input_type -> lobby.SubscribeRequest
	16, // 17: lobby.LobbyService.SendKeyPress:input_type -> lobby.SendKeyPressRequest
	18, // 18: lobby.LobbyService.ResumeGame:input_type -> lobby.ResumeGameRequest
	5,  // 19: lobby.LobbyService.CreateLobby:output_type -> lobby.CreateLobbyResponse
	7,  // 20: lobby.LobbyService.JoinLobby:output_type -> lobby.JoinLobbyResponse
	9,  // 21: lobby.LobbyService.LeaveLobby:output_type -> lobby.LeaveLobbyResponse
	11, // 22: lobby.LobbyService.EditPlayer:output_type -> lobby.EditPlayerResponse
	13, // 23: lobby.LobbyService.ReadyPlayer:output_type -> lobby.ReadyPlayerResponse
	15, // 24: lobby.LobbyService.Subscribe:output_type -> lobby.LobbyEvent
	17, // 25: lobby.LobbyService.SendKeyPress:output_type -> lobby.SendKeyPressResponse
	19, // 26: lobby.LobbyService.ResumeGame:output_type -> lobby.ResumeGameResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_common_proto_lobby_lobby_proto_init() }
func file_common_proto_lobby_lobby_proto_init() {
	if File_common_proto_lobby_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_lobby_lobby_proto_rawDesc), len(file_common_proto_lobby_lobby_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_lobby_lobby_proto_goTypes,
		DependencyIndexes: file_common_proto_lobby_lobby_proto_depIdxs,
		EnumInfos:         file_common_proto_lobby_lobby_proto_enumTypes,
		MessageInfos:      file_common_proto_lobby_lobby_proto_msgTypes,
	}.Build()
	File_common_proto_lobby_lobby_proto = out.File
	file_common_proto_lobby_lobby_proto_goTypes = nil
	file_common_proto_lobby_lobby_proto_depIdxs = nil
}
