// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/proto/lobby/lobby.proto

package lobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for lobby management.
type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *CreateLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLobbyResponse) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

type Lobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players       []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Host          *Player                `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Snippet       string                 `protobuf:"bytes,4,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lobby) Reset() {
	*x = Lobby{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lobby) ProtoMessage() {}

func (x *Lobby) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lobby.ProtoReflect.Descriptor instead.
func (*Lobby) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *Lobby) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lobby) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Lobby) GetHost() *Player {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Lobby) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type Player struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsReady           bool                   `protobuf:"varint,2,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	AllowedCharacters string                 `protobuf:"bytes,3,opt,name=allowed_characters,json=allowedCharacters,proto3" json:"allowed_characters,omitempty"`
	BlockedCharacters string                 `protobuf:"bytes,4,opt,name=blocked_characters,json=blockedCharacters,proto3" json:"blocked_characters,omitempty"`
	CanDelete         bool                   `protobuf:"varint,5,opt,name=can_delete,json=canDelete,proto3" json:"can_delete,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *Player) GetAllowedCharacters() string {
	if x != nil {
		return x.AllowedCharacters
	}
	return ""
}

func (x *Player) GetBlockedCharacters() string {
	if x != nil {
		return x.BlockedCharacters
	}
	return ""
}

func (x *Player) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *SubscribeRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type LobbyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lobby         *Lobby                 `protobuf:"bytes,1,opt,name=lobby,proto3" json:"lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyEvent) Reset() {
	*x = LobbyEvent{}
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyEvent) ProtoMessage() {}

func (x *LobbyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lobby_lobby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyEvent.ProtoReflect.Descriptor instead.
func (*LobbyEvent) Descriptor() ([]byte, []int) {
	return file_common_proto_lobby_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *LobbyEvent) GetLobby() *Lobby {
	if x != nil {
		return x.Lobby
	}
	return nil
}

var File_common_proto_lobby_lobby_proto protoreflect.FileDescriptor

const file_common_proto_lobby_lobby_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/proto/lobby/lobby.proto\x12\x05lobby\"P\n" +
	"\x12CreateLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"9\n" +
	"\x13CreateLobbyResponse\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby\"}\n" +
	"\x05Lobby\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\aplayers\x18\x02 \x03(\v2\r.lobby.PlayerR\aplayers\x12!\n" +
	"\x04host\x18\x03 \x01(\v2\r.lobby.PlayerR\x04host\x12\x18\n" +
	"\asnippet\x18\x04 \x01(\tR\asnippet\"\xb4\x01\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bis_ready\x18\x02 \x01(\bR\aisReady\x12-\n" +
	"\x12allowed_characters\x18\x03 \x01(\tR\x11allowedCharacters\x12-\n" +
	"\x12blocked_characters\x18\x04 \x01(\tR\x11blockedCharacters\x12\x1d\n" +
	"\n" +
	"can_delete\x18\x05 \x01(\bR\tcanDelete\"N\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"0\n" +
	"\n" +
	"LobbyEvent\x12\"\n" +
	"\x05lobby\x18\x01 \x01(\v2\f.lobby.LobbyR\x05lobby2\x8f\x01\n" +
	"\fLobbyService\x12D\n" +
	"\vCreateLobby\x12\x19.lobby.CreateLobbyRequest\x1a\x1a.lobby.CreateLobbyResponse\x129\n" +
	"\tSubscribe\x12\x17.lobby.SubscribeRequest\x1a\x11.lobby.LobbyEvent0\x01B/Z-github.com/sceredi/co-type/common/proto/lobbyb\x06proto3"

var (
	file_common_proto_lobby_lobby_proto_rawDescOnce sync.Once
	file_common_proto_lobby_lobby_proto_rawDescData []byte
)

func file_common_proto_lobby_lobby_proto_rawDescGZIP() []byte {
	file_common_proto_lobby_lobby_proto_rawDescOnce.Do(func() {
		file_common_proto_lobby_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_lobby_lobby_proto_rawDesc), len(file_common_proto_lobby_lobby_proto_rawDesc)))
	})
	return file_common_proto_lobby_lobby_proto_rawDescData
}

var file_common_proto_lobby_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_lobby_lobby_proto_goTypes = []any{
	(*CreateLobbyRequest)(nil),  // 0: lobby.CreateLobbyRequest
	(*CreateLobbyResponse)(nil), // 1: lobby.CreateLobbyResponse
	(*Lobby)(nil),               // 2: lobby.Lobby
	(*Player)(nil),              // 3: lobby.Player
	(*SubscribeRequest)(nil),    // 4: lobby.SubscribeRequest
	(*LobbyEvent)(nil),          // 5: lobby.LobbyEvent
}
var file_common_proto_lobby_lobby_proto_depIdxs = []int32{
	2, // 0: lobby.CreateLobbyResponse.lobby:type_name -> lobby.Lobby
	3, // 1: lobby.Lobby.players:type_name -> lobby.Player
	3, // 2: lobby.Lobby.host:type_name -> lobby.Player
	2, // 3: lobby.LobbyEvent.lobby:type_name -> lobby.Lobby
	0, // 4: lobby.LobbyService.CreateLobby:input_type -> lobby.CreateLobbyRequest
	4, // 5: lobby.LobbyService.Subscribe:input_type -> lobby.SubscribeRequest
	1, // 6: lobby.LobbyService.CreateLobby:output_type -> lobby.CreateLobbyResponse
	5, // 7: lobby.LobbyService.Subscribe:output_type -> lobby.LobbyEvent
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_proto_lobby_lobby_proto_init() }
func file_common_proto_lobby_lobby_proto_init() {
	if File_common_proto_lobby_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_lobby_lobby_proto_rawDesc), len(file_common_proto_lobby_lobby_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_lobby_lobby_proto_goTypes,
		DependencyIndexes: file_common_proto_lobby_lobby_proto_depIdxs,
		MessageInfos:      file_common_proto_lobby_lobby_proto_msgTypes,
	}.Build()
	File_common_proto_lobby_lobby_proto = out.File
	file_common_proto_lobby_lobby_proto_goTypes = nil
	file_common_proto_lobby_lobby_proto_depIdxs = nil
}
