// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/proto/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelopes for communication between clients and the game server.
type ServerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEnvelope_Create
	//	*ServerEnvelope_Join
	Payload       isServerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEnvelope) Reset() {
	*x = ServerEnvelope{}
	mi := &file_common_proto_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEnvelope) ProtoMessage() {}

func (x *ServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEnvelope.ProtoReflect.Descriptor instead.
func (*ServerEnvelope) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *ServerEnvelope) GetPayload() isServerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEnvelope) GetCreate() *CreateLobby {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *ServerEnvelope) GetJoin() *JoinLobby {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Join); ok {
			return x.Join
		}
	}
	return nil
}

type isServerEnvelope_Payload interface {
	isServerEnvelope_Payload()
}

type ServerEnvelope_Create struct {
	Create *CreateLobby `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type ServerEnvelope_Join struct {
	Join *JoinLobby `protobuf:"bytes,2,opt,name=join,proto3,oneof"`
}

func (*ServerEnvelope_Create) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Join) isServerEnvelope_Payload() {}

// Envelopes for communication from the game server to clients.
type ClientEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientEnvelope_CreateAck
	//	*ClientEnvelope_JoinAck
	Payload       isClientEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEnvelope) Reset() {
	*x = ClientEnvelope{}
	mi := &file_common_proto_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnvelope) ProtoMessage() {}

func (x *ClientEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnvelope.ProtoReflect.Descriptor instead.
func (*ClientEnvelope) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *ClientEnvelope) GetPayload() isClientEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientEnvelope) GetCreateAck() *CreateLobbyAck {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_CreateAck); ok {
			return x.CreateAck
		}
	}
	return nil
}

func (x *ClientEnvelope) GetJoinAck() *JoinLobbyAck {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_JoinAck); ok {
			return x.JoinAck
		}
	}
	return nil
}

type isClientEnvelope_Payload interface {
	isClientEnvelope_Payload()
}

type ClientEnvelope_CreateAck struct {
	CreateAck *CreateLobbyAck `protobuf:"bytes,1,opt,name=create_ack,json=createAck,proto3,oneof"`
}

type ClientEnvelope_JoinAck struct {
	JoinAck *JoinLobbyAck `protobuf:"bytes,2,opt,name=join_ack,json=joinAck,proto3,oneof"`
}

func (*ClientEnvelope_CreateAck) isClientEnvelope_Payload() {}

func (*ClientEnvelope_JoinAck) isClientEnvelope_Payload() {}

// Messages for lobby management.
type CreateLobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobby) Reset() {
	*x = CreateLobby{}
	mi := &file_common_proto_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobby) ProtoMessage() {}

func (x *CreateLobby) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobby.ProtoReflect.Descriptor instead.
func (*CreateLobby) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLobby) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *CreateLobby) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// Acknowledgment for lobby creation.
type CreateLobbyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyAck) Reset() {
	*x = CreateLobbyAck{}
	mi := &file_common_proto_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyAck) ProtoMessage() {}

func (x *CreateLobbyAck) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyAck.ProtoReflect.Descriptor instead.
func (*CreateLobbyAck) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLobbyAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateLobbyAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Messages for joining a lobby.
type JoinLobby struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobby) Reset() {
	*x = JoinLobby{}
	mi := &file_common_proto_game_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobby) ProtoMessage() {}

func (x *JoinLobby) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobby.ProtoReflect.Descriptor instead.
func (*JoinLobby) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *JoinLobby) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *JoinLobby) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// Acknowledgment for joining a lobby.
type JoinLobbyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyAck) Reset() {
	*x = JoinLobbyAck{}
	mi := &file_common_proto_game_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyAck) ProtoMessage() {}

func (x *JoinLobbyAck) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyAck.ProtoReflect.Descriptor instead.
func (*JoinLobbyAck) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{5}
}

var File_common_proto_game_game_proto protoreflect.FileDescriptor

const file_common_proto_game_game_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/proto/game/game.proto\x12\x04game\"o\n" +
	"\x0eServerEnvelope\x12+\n" +
	"\x06create\x18\x01 \x01(\v2\x11.game.CreateLobbyH\x00R\x06create\x12%\n" +
	"\x04join\x18\x02 \x01(\v2\x0f.game.JoinLobbyH\x00R\x04joinB\t\n" +
	"\apayload\"\x83\x01\n" +
	"\x0eClientEnvelope\x125\n" +
	"\n" +
	"create_ack\x18\x01 \x01(\v2\x14.game.CreateLobbyAckH\x00R\tcreateAck\x12/\n" +
	"\bjoin_ack\x18\x02 \x01(\v2\x12.game.JoinLobbyAckH\x00R\ajoinAckB\t\n" +
	"\apayload\"I\n" +
	"\vCreateLobby\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"D\n" +
	"\x0eCreateLobbyAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\tJoinLobby\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"\x0e\n" +
	"\fJoinLobbyAck2G\n" +
	"\vGameService\x128\n" +
	"\x06Manage\x12\x14.game.ServerEnvelope\x1a\x14.game.ClientEnvelope(\x010\x01B.Z,github.com/sceredi/co-type/common/proto/gameb\x06proto3"

var (
	file_common_proto_game_game_proto_rawDescOnce sync.Once
	file_common_proto_game_game_proto_rawDescData []byte
)

func file_common_proto_game_game_proto_rawDescGZIP() []byte {
	file_common_proto_game_game_proto_rawDescOnce.Do(func() {
		file_common_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_game_game_proto_rawDesc), len(file_common_proto_game_game_proto_rawDesc)))
	})
	return file_common_proto_game_game_proto_rawDescData
}

var file_common_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_game_game_proto_goTypes = []any{
	(*ServerEnvelope)(nil), // 0: game.ServerEnvelope
	(*ClientEnvelope)(nil), // 1: game.ClientEnvelope
	(*CreateLobby)(nil),    // 2: game.CreateLobby
	(*CreateLobbyAck)(nil), // 3: game.CreateLobbyAck
	(*JoinLobby)(nil),      // 4: game.JoinLobby
	(*JoinLobbyAck)(nil),   // 5: game.JoinLobbyAck
}
var file_common_proto_game_game_proto_depIdxs = []int32{
	2, // 0: game.ServerEnvelope.create:type_name -> game.CreateLobby
	4, // 1: game.ServerEnvelope.join:type_name -> game.JoinLobby
	3, // 2: game.ClientEnvelope.create_ack:type_name -> game.CreateLobbyAck
	5, // 3: game.ClientEnvelope.join_ack:type_name -> game.JoinLobbyAck
	0, // 4: game.GameService.Manage:input_type -> game.ServerEnvelope
	1, // 5: game.GameService.Manage:output_type -> game.ClientEnvelope
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_proto_game_game_proto_init() }
func file_common_proto_game_game_proto_init() {
	if File_common_proto_game_game_proto != nil {
		return
	}
	file_common_proto_game_game_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerEnvelope_Create)(nil),
		(*ServerEnvelope_Join)(nil),
	}
	file_common_proto_game_game_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientEnvelope_CreateAck)(nil),
		(*ClientEnvelope_JoinAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_game_game_proto_rawDesc), len(file_common_proto_game_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_game_game_proto_goTypes,
		DependencyIndexes: file_common_proto_game_game_proto_depIdxs,
		MessageInfos:      file_common_proto_game_game_proto_msgTypes,
	}.Build()
	File_common_proto_game_game_proto = out.File
	file_common_proto_game_game_proto_goTypes = nil
	file_common_proto_game_game_proto_depIdxs = nil
}
