// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: common/proto/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for lobby management.
type CreateLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_common_proto_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *CreateLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// Acknowledgment for lobby creation.
type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_common_proto_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{1}
}

// Messages for joining a lobby.
type JoinLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyRequest) Reset() {
	*x = JoinLobbyRequest{}
	mi := &file_common_proto_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyRequest) ProtoMessage() {}

func (x *JoinLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyRequest.ProtoReflect.Descriptor instead.
func (*JoinLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *JoinLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *JoinLobbyRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// Acknowledgment for joining a lobby.
type JoinLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLobbyResponse) Reset() {
	*x = JoinLobbyResponse{}
	mi := &file_common_proto_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLobbyResponse) ProtoMessage() {}

func (x *JoinLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLobbyResponse.ProtoReflect.Descriptor instead.
func (*JoinLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_game_game_proto_rawDescGZIP(), []int{3}
}

var File_common_proto_game_game_proto protoreflect.FileDescriptor

const file_common_proto_game_game_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/proto/game/game.proto\x12\x04game\"P\n" +
	"\x12CreateLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"\x15\n" +
	"\x13CreateLobbyResponse\"N\n" +
	"\x10JoinLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"\x13\n" +
	"\x11JoinLobbyResponse2Q\n" +
	"\vGameService\x12B\n" +
	"\vCreateLobby\x12\x18.game.CreateLobbyRequest\x1a\x19.game.CreateLobbyResponseB.Z,github.com/sceredi/co-type/common/proto/gameb\x06proto3"

var (
	file_common_proto_game_game_proto_rawDescOnce sync.Once
	file_common_proto_game_game_proto_rawDescData []byte
)

func file_common_proto_game_game_proto_rawDescGZIP() []byte {
	file_common_proto_game_game_proto_rawDescOnce.Do(func() {
		file_common_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_game_game_proto_rawDesc), len(file_common_proto_game_game_proto_rawDesc)))
	})
	return file_common_proto_game_game_proto_rawDescData
}

var file_common_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_game_game_proto_goTypes = []any{
	(*CreateLobbyRequest)(nil),  // 0: game.CreateLobbyRequest
	(*CreateLobbyResponse)(nil), // 1: game.CreateLobbyResponse
	(*JoinLobbyRequest)(nil),    // 2: game.JoinLobbyRequest
	(*JoinLobbyResponse)(nil),   // 3: game.JoinLobbyResponse
}
var file_common_proto_game_game_proto_depIdxs = []int32{
	0, // 0: game.GameService.CreateLobby:input_type -> game.CreateLobbyRequest
	1, // 1: game.GameService.CreateLobby:output_type -> game.CreateLobbyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_game_game_proto_init() }
func file_common_proto_game_game_proto_init() {
	if File_common_proto_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_game_game_proto_rawDesc), len(file_common_proto_game_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_game_game_proto_goTypes,
		DependencyIndexes: file_common_proto_game_game_proto_depIdxs,
		MessageInfos:      file_common_proto_game_game_proto_msgTypes,
	}.Build()
	File_common_proto_game_game_proto = out.File
	file_common_proto_game_game_proto_goTypes = nil
	file_common_proto_game_game_proto_depIdxs = nil
}
