// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: common/proto/control/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for server registration.
type RegisterServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int64                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	LobbyIds      []string               `protobuf:"bytes,4,rep,name=lobby_ids,json=lobbyIds,proto3" json:"lobby_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServerRequest) Reset() {
	*x = RegisterServerRequest{}
	mi := &file_common_proto_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerRequest) ProtoMessage() {}

func (x *RegisterServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterServerRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterServerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterServerRequest) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterServerRequest) GetLobbyIds() []string {
	if x != nil {
		return x.LobbyIds
	}
	return nil
}

// Acknowledgment for server registration.
type RegisterServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServerResponse) Reset() {
	*x = RegisterServerResponse{}
	mi := &file_common_proto_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerResponse) ProtoMessage() {}

func (x *RegisterServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterServerResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Messages for lobby registration with the broker.
type RegisterLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLobbyRequest) Reset() {
	*x = RegisterLobbyRequest{}
	mi := &file_common_proto_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLobbyRequest) ProtoMessage() {}

func (x *RegisterLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLobbyRequest.ProtoReflect.Descriptor instead.
func (*RegisterLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

func (x *RegisterLobbyRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

// Response for lobby registration.
type RegisterLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterLobbyResponse) Reset() {
	*x = RegisterLobbyResponse{}
	mi := &file_common_proto_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterLobbyResponse) ProtoMessage() {}

func (x *RegisterLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterLobbyResponse.ProtoReflect.Descriptor instead.
func (*RegisterLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterLobbyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to unregister a lobby from the broker.
type UnregisterLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LobbyId       string                 `protobuf:"bytes,1,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterLobbyRequest) Reset() {
	*x = UnregisterLobbyRequest{}
	mi := &file_common_proto_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterLobbyRequest) ProtoMessage() {}

func (x *UnregisterLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterLobbyRequest.ProtoReflect.Descriptor instead.
func (*UnregisterLobbyRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterLobbyRequest) GetLobbyId() string {
	if x != nil {
		return x.LobbyId
	}
	return ""
}

// Response for lobby unregistration.
type UnregisterLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterLobbyResponse) Reset() {
	*x = UnregisterLobbyResponse{}
	mi := &file_common_proto_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterLobbyResponse) ProtoMessage() {}

func (x *UnregisterLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterLobbyResponse.ProtoReflect.Descriptor instead.
func (*UnregisterLobbyResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterLobbyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat request sent periodically by a server to signal it is alive and report its current load.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Load          int64                  `protobuf:"varint,2,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_common_proto_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeartbeatRequest) GetLoad() int64 {
	if x != nil {
		return x.Load
	}
	return 0
}

// Acknowledgment for a heartbeat.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_common_proto_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_control_control_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_common_proto_control_control_proto protoreflect.FileDescriptor

const file_common_proto_control_control_proto_rawDesc = "" +
	"\n" +
	"\"common/proto/control/control.proto\x12\acontrol\"p\n" +
	"\x15RegisterServerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x03R\x04port\x12\x1b\n" +
	"\tlobby_ids\x18\x04 \x03(\tR\blobbyIds\"L\n" +
	"\x16RegisterServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x14RegisterLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\"K\n" +
	"\x15RegisterLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x16UnregisterLobbyRequest\x12\x19\n" +
	"\blobby_id\x18\x01 \x01(\tR\alobbyId\"M\n" +
	"\x17UnregisterLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x10HeartbeatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04load\x18\x02 \x01(\x03R\x04load\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcd\x02\n" +
	"\x0eControlService\x12Q\n" +
	"\x0eRegisterServer\x12\x1e.control.RegisterServerRequest\x1a\x1f.control.RegisterServerResponse\x12N\n" +
	"\rRegisterLobby\x12\x1d.control.RegisterLobbyRequest\x1a\x1e.control.RegisterLobbyResponse\x12T\n" +
	"\x0fUnregisterLobby\x12\x1f.control.UnregisterLobbyRequest\x1a .control.UnregisterLobbyResponse\x12B\n" +
	"\tHeartbeat\x12\x19.control.HeartbeatRequest\x1a\x1a.control.HeartbeatResponseB1Z/github.com/sceredi/co-type/common/proto/controlb\x06proto3"

var (
	file_common_proto_control_control_proto_rawDescOnce sync.Once
	file_common_proto_control_control_proto_rawDescData []byte
)

func file_common_proto_control_control_proto_rawDescGZIP() []byte {
	file_common_proto_control_control_proto_rawDescOnce.Do(func() {
		file_common_proto_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_control_control_proto_rawDesc), len(file_common_proto_control_control_proto_rawDesc)))
	})
	return file_common_proto_control_control_proto_rawDescData
}

var file_common_proto_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_proto_control_control_proto_goTypes = []any{
	(*RegisterServerRequest)(nil),   // 0: control.RegisterServerRequest
	(*RegisterServerResponse)(nil),  // 1: control.RegisterServerResponse
	(*RegisterLobbyRequest)(nil),    // 2: control.RegisterLobbyRequest
	(*RegisterLobbyResponse)(nil),   // 3: control.RegisterLobbyResponse
	(*UnregisterLobbyRequest)(nil),  // 4: control.UnregisterLobbyRequest
	(*UnregisterLobbyResponse)(nil), // 5: control.UnregisterLobbyResponse
	(*HeartbeatRequest)(nil),        // 6: control.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 7: control.HeartbeatResponse
}
var file_common_proto_control_control_proto_depIdxs = []int32{
	0, // 0: control.ControlService.RegisterServer:input_type -> control.RegisterServerRequest
	2, // 1: control.ControlService.RegisterLobby:input_type -> control.RegisterLobbyRequest
	4, // 2: control.ControlService.UnregisterLobby:input_type -> control.UnregisterLobbyRequest
	6, // 3: control.ControlService.Heartbeat:input_type -> control.HeartbeatRequest
	1, // 4: control.ControlService.RegisterServer:output_type -> control.RegisterServerResponse
	3, // 5: control.ControlService.RegisterLobby:output_type -> control.RegisterLobbyResponse
	5, // 6: control.ControlService.UnregisterLobby:output_type -> control.UnregisterLobbyResponse
	7, // 7: control.ControlService.Heartbeat:output_type -> control.HeartbeatResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_control_control_proto_init() }
func file_common_proto_control_control_proto_init() {
	if File_common_proto_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_control_control_proto_rawDesc), len(file_common_proto_control_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_control_control_proto_goTypes,
		DependencyIndexes: file_common_proto_control_control_proto_depIdxs,
		MessageInfos:      file_common_proto_control_control_proto_msgTypes,
	}.Build()
	File_common_proto_control_control_proto = out.File
	file_common_proto_control_control_proto_goTypes = nil
	file_common_proto_control_control_proto_depIdxs = nil
}
